const cndconstants = {
  CONDOMINIUM_PAYLOAD: "CONDOMINIUM_PAYLOAD",
  SLIDER_CHANGE_PRICE: "SLIDER_CHANGE_PRICE",
  SLIDER_CHANGE_HOUSE_AREA: "SLIDER_CHANGE_HOUSE_AREA",
  SLIDER_CHANGE_LOT_AREA: "SLIDER_CHANGE_LOT_AREA",
  TYPE_SELECT_CHANGE: "TYPE_SELECT_CHANGE",
  SELLING_SELECT_CHANGE: "SELLING_SELECT_CHANGE",
  BED_SELECT_CHANGE: "BED_SELECT_CHANGE",
  BATH_SELECT_CHANGE: "BATH_SELECT_CHANGE",
  CAR_SELECT_CHANGE: "CAR_SELECT_CHANGE",
  SEARCH_CLICK: "SEARCH_CLICK",
  RESET_CLICK: "RESET_CLICK",
};

export default cndconstants;
